# Generated by Django 4.1.6 on 2023-02-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_energy', models.FloatField()),
                ('meter_date', models.DateTimeField()),
                ('meter_id', models.IntegerField()),
            ],
        ),
    ]
